name: XmlDialplanGenerator
description: A sample command-line application
dependencies:
  OpenReceptionFramework:
    git:
      ref: master
      url: https://github.com/AdaHeads/OpenReceptionFramework.git
  args: any
  libdialplan:
    git:
      ref: master
      url: https://github.com/AdaHeads/libdialplan.git
  path: any
  route: any
  xml: 1.0.0
